AppClub/urls.py
from django.urls import path
from AppClub.views import *
from authentication.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", inicio, name="Inicio"),
    path("about_us/", about_us, name="about_us"),
    path("contacto/", contacto, name="contacto"),
    path("listarNoticias/", NoticiaList.as_view(), name="listarNoticias"),
    path("detallarNoticias/<pk>/", NoticiaDetail.as_view(), name="detallarNoticias"),
    path("crearNoticias/", NoticiaCreate.as_view(), name="crearNoticias"),
    path(
        "actualizarNoticias/<pk>/", NoticiaUpdate.as_view(), name="actualizarNoticias"
    ),
    path("eliminarNoticias/<pk>/", NoticiaDelete.as_view(), name="eliminarNoticias"),
    path("listarDeportes/", DeporteList.as_view(), name="listarDeportes"),
    path("detalleDeportes/<pk>/", DeporteDetail.as_view(), name="detallarDeportes"),
    path("crearDeportes/", DeporteCreate.as_view(), name="crearDeportes"),
    path(
        "actualizarDeportes/<pk>/", DeporteUpdate.as_view(), name="actualizarDeportes"
    ),
    path("eliminarDeportes/<pk>/", DeporteDelete.as_view(), name="eliminarDeportes"),
    path("listarEventos/", EventoList.as_view(), name="listarEventos"),
    path("detalleEventos/<pk>/", EventoDetail.as_view(), name="detallarEventos"),
    path("crearEventos/", EventoCreate.as_view(), name="crearEventos"),
    path("actualizarEventos/<pk>/", EventoUpdate.as_view(), name="actualizarEvento"),
    path("eliminarEventos/<pk>/", EventoDelete.as_view(), name="eliminarEventos"),
    path(
        "noticia/<int:noticia_id>/comentar/",
        CrearComentario.as_view(),
        name="CrearComentario",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TerceraPinciroli/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from authentication.views import Error404


handler404 = Error404

urlpatterns = [
    path("admin/", admin.site.urls),
    path("AppClub/", include("AppClub.urls")),
    path("authentication/", include("authentication.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

AppClub/models.py
from django.db import models


class Deporte(models.Model):
    nombre = models.CharField(max_length=60)
    descripcion = models.CharField(max_length=60)
    categoria = models.CharField(max_length=60)

    def __str__(self):
        return f"{self.nombre}"


class Noticia(models.Model):
    titulo = models.CharField(max_length=100)
    subtitulo = models.CharField(max_length=100)
    fecha = models.DateField()
    tema = models.CharField(max_length=100)
    desarrollo = models.TextField(max_length=600)
    imagen = models.ImageField(upload_to="noticias", null=True, blank=True)
    pie_de_foto = models.CharField(max_length=100)
    autor = models.CharField(max_length=100, null=True)

    def __str__(self):
        return f"{self.titulo}"


class Evento(models.Model):
    titulo = models.CharField(max_length=100)
    fecha = models.DateField()
    descripcion = models.TextField()
    deporte = models.ForeignKey(Deporte, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.titulo} - {self.fecha}"


opciones_consultas = [
    [0, "Consulta"],
    [1, "Reclamo"],
    [2, "Sugerencia"],
    [3, "Felicitaciones"],
]


class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensajes = models.TextField()
    avisos = models.BooleanField()

    def __str__(self):
        return f"{self.nombre}"


class Comentario(models.Model):
    from authentication.models import Perfil

    autor = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE)
    comentario = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comentario de {self.autor.username} en {self.noticia.titulo}"

    class Meta:
        ordering = ["-fecha"]

AppClub/forms.py
from django import forms
from .models import Noticia, Contacto, Comentario


class NoticiaFormulario(forms.ModelForm):
    class Meta:
        model = Noticia
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(NoticiaFormulario, self).__init__(*args, **kwargs)
        self.fields["imagen"].widget.attrs["accept"] = "image/*"


class DeporteFormulario(forms.Form):
    nombre = forms.CharField(max_length=60)
    descripcion = forms.CharField(max_length=60)
    fecha_inicio = forms.DateField()
    fecha_fin = forms.DateField()


class EventoFormulario(forms.Form):
    titulo = forms.CharField(max_length=100)
    fecha = forms.DateField()


class ContactoFormulario(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = "__all__"

    mensajes = forms.CharField(
        label="",
        widget=forms.Textarea(attrs={"placeholder": "Escribe tu mensaje..."}),
    )


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ["comentario"]

    comentario = forms.CharField(
        label="",
        widget=forms.Textarea(attrs={"placeholder": "Comentario"}),
    )

AppClub/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
from django.views.generic import ListView, View
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from .models import Noticia, Deporte, Evento, Comentario
from .forms import NoticiaFormulario, ContactoFormulario, ComentarioForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


def inicio(req):
    return render(req, "inicio.html")


def about_us(req):
    return render(req, "about_us.html")


def contacto(req):
    data = {"form": ContactoFormulario()}

    if req.method == "POST":
        formulario = ContactoFormulario(data=req.POST)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = "Mensaje enviado."
        else:
            data["form"] = formulario

    return render(req, "contacto.html", data)


class NoticiaList(ListView):
    model = Noticia
    template_name = "noticia_list.html"
    context_object_name = "noticias"


class NoticiaDetail(DetailView):
    model = Noticia
    template_name = "noticia_detail.html"
    context_object_name = "noticia"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["comentarios"] = Comentario.objects.filter(noticia=self.object)
        context["comentario_form"] = ComentarioForm()  # Agrega esta línea
        return context


class NoticiaCreate(LoginRequiredMixin, CreateView):
    model = Noticia
    template_name = "noticia_create.html"
    form_class = NoticiaFormulario
    success_url = reverse_lazy("Inicio")

    def form_valid(self, form):
        # Procesa la imagen si se ha cargado
        if "imagen" in self.request.FILES:
            form.instance.imagen = self.request.FILES["imagen"]
        return super().form_valid(form)


class NoticiaUpdate(LoginRequiredMixin, UpdateView):
    model = Noticia
    template_name = "noticia_update.html"
    form_class = NoticiaFormulario
    success_url = reverse_lazy("listarNoticias")

    def form_valid(self, form):
        # Procesa la imagen si se ha cargado
        if "imagen" in self.request.FILES:
            form.instance.imagen = self.request.FILES["imagen"]
        return super().form_valid(form)


class NoticiaDelete(DeleteView):
    model = Noticia
    template_name = "noticia_delete.html"
    success_url = reverse_lazy("listarNoticias")


class DeporteList(ListView):
    model = Deporte
    template_name = "deporte_list.html"
    context_object_name = "deportes"


class DeporteDetail(DetailView):
    model = Deporte
    template_name = "deporte_detail.html"
    context_object_name = "deporte"


class DeporteCreate(LoginRequiredMixin, CreateView):
    model = Deporte
    template_name = "deporte_create.html"
    fields = "__all__"
    success_url = reverse_lazy("listarDeportes")


class DeporteUpdate(LoginRequiredMixin, UpdateView):
    model = Deporte
    template_name = "deporte_update.html"
    fields = "__all__"
    success_url = reverse_lazy("listarDeportes")


class DeporteDelete(LoginRequiredMixin, DeleteView):
    model = Deporte
    template_name = "deporte_delete.html"
    success_url = reverse_lazy("listarDeportes")


class EventoList(ListView):
    model = Evento
    template_name = "evento_list.html"
    context_object_name = "eventos"


class EventoDetail(DetailView):
    model = Evento
    template_name = "evento_detail.html"
    context_object_name = "evento"


class EventoCreate(LoginRequiredMixin, CreateView):
    model = Evento
    template_name = "evento_Create.html"
    fields = "__all__"
    success_url = reverse_lazy("listarEventos")


class EventoUpdate(LoginRequiredMixin, UpdateView):
    model = Evento
    template_name = "evento_update.html"
    fields = "__all__"
    success_url = reverse_lazy("listarEventos")


class EventoDelete(LoginRequiredMixin, DeleteView):
    model = Evento
    template_name = "evento_delete.html"
    success_url = reverse_lazy("listarEventos")


class CrearComentario(View):
    def post(self, req, noticia_id):
        noticia = Noticia.objects.get(pk=noticia_id)
        form = ComentarioForm(req.POST)
        if form.is_valid():
            comentario = form.cleaned_data["comentario"]
            Comentario.objects.create(
                noticia=noticia, autor=req.user, comentario=comentario
            )
        return redirect("detallarNoticias", pk=noticia_id)

AppClub/templates/contacto.html
{% extends 'padre.html' %}

{% block ContenidoQueCambia %}
<div class="row mt-4 px-4 px-lg-5 gx-4 gx-lg-5 align-items-center mx-auto my-5">
<h2>Contactenos</h2>
<form action="" class="formulario_contacto" method="post"> {% csrf_token %}
    {{form.as_p}}

    <button type="submit" class="btn btn-primary"> Crear </button>
</form>
<p><strong>{{mensaje}}</strong></p>
</div>

{% endblock ContenidoQueCambia %}

AppClub/templates/deporte_detail.html
{% extends 'padre.html' %}
{% load static %}
{% block ContenidoQueCambia %}
<div class="row mt-4 px-4 px-lg-5 gx-4 gx-lg-5 align-items-center mx-auto my-5">
        <div class="col-lg-7">
            <img src="{% static 'default_evento.jpg' %}" width="500" height="300" alt="Avatar por defecto">
        </div>
        <div class="col-lg-5">
        <p><strong style="text-transform: uppercase;">{{deporte.categoria}}</strong></p>
            <h2 class="font-weight-light">{{deporte.nombre}}</h2>
            <p>{{deporte.descripcion}}</p>
        {% if user.is_authenticated %}
        <form method="post" action="{% url 'agregar_deporte' %}">
            {% csrf_token %}
            <input type="hidden" name="deporte" value="{{deporte.id}}">
            <button type="submit" class="btn btn-primary btn-block">Anotarme</button>
        </form>
        {% else %}
        <p>¿Quieres Anotarte? <a class="btn btn-primary btn-block" href="{% url 'login' %}">Inicia Sesión</a></p> 
        {% endif %}
        </div>
</div>
{% endblock ContenidoQueCambia %}

AppClub/templates/deporte_list.html
{% extends 'padre.html' %}

{% block ContenidoQueCambia %}
<div class="container mt-4 mb-4">
    <div class="row">
        {% for deporte in deportes %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <div class="card-body">
                        <h3 class="card-title">{{ deporte.nombre }}</h3>
                        <p class="card-text">{{ deporte.categoria }}</p>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <a class="btn btn-primary btn-block" href="{% url 'detallarDeportes' pk=deporte.pk %}">Ver más</a>
                        {% if user.is_staff %}
                            <a class="btn btn-secondary btn-block" href="{% url 'actualizarDeportes' deporte.id %}">Editar</a>
                            <form action="{% url 'eliminarDeportes' deporte.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-secondary btn-block">Eliminar</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% empty %}
            <p>No hay deportes disponibles.</p>
        {% endfor %}
    </div>
</div>

{% endblock ContenidoQueCambia %}

AppClub/templates/deporte_update.html
{% extends 'padre.html' %}

{% block ContenidoQueCambia %}
<form action="{% url 'actualizarDeportes' pk=deporte.id %}" method="post"> {% csrf_token %}
    {{form.as_p}}

    <button type="submit"> Actualizar </button>
</form>

{% endblock ContenidoQueCambia %}

AppClub/templates/editarDeporte.html
{% extends 'padre.html' %}

{% block ContenidoQueCambia %}
<form action="{% url 'editarDeportes' id %}" method="post"> {% csrf_token %}

    {{miFormulario.as_p}}

    <button type="submit"> Actualizar </button>
</form>

{% endblock ContenidoQueCambia %}

AppClub/templates/error_404.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error 404 - Página no encontrada</title>
</head>

<body>
    <h1>Error 404 - Página no encontrada</h1>
    <p>No se ha encontrado la página que estás buscando.</p>
    <p>La página que intentas acceder no existe o ha sido eliminada.</p>
</body>

</html>

AppClub/templates/evento_delete.html
{% extends 'padre.html' %}

{% block ContenidoQueCambia %}
<form action="{% url 'eliminarEventos' pk=evento.id %}" method="post"> {% csrf_token %}
    {{form.as_p}}

    <p>Está seguro que quiere eliminar el evento?</p>

    <button type="submit"> Confirmar </button>
    <button>="<a href="{% url 'Inicio' %}"></a>" Cancelar </button>
</form>

{% endblock ContenidoQueCambia %}

AppClub/templates/evento_detail.html
{% extends 'padre.html' %}
{% load static %}
{% block ContenidoQueCambia %}
<div class="row mt-4 px-4 px-lg-5 gx-4 gx-lg-5 align-items-center mx-auto my-5">
        <div class="col-lg-7">
            <img src="{% static 'default_evento.jpg' %}" width="500" height="300" alt="Avatar por defecto">
        </div>
        <div class="col-lg-5">
        <p><strong style="text-transform: uppercase;">{{evento.deporte}}</strong></p>
            <h2 class="font-weight-light">{{evento.titulo}}</h2>
            <h6>Evento programado para el día {{evento.fecha}}</h6>
            <p>{{evento.descripcion}}</p>
{% if user.is_authenticated %}
        <form method="post" action="{% url 'agregar_evento' %}">
            {% csrf_token %}
            <input type="hidden" name="evento" value="{{evento.id}}">
            <button type="submit" class="btn btn-primary btn-block">Reservar</button>
        </form>
        {% else %}
        <p>¿Quieres Reservar? <a class="btn btn-primary btn-block" href="{% url 'login' %}">Inicia Sesión</a></p> 
        {% endif %}
        </div>
</div>
{% endblock ContenidoQueCambia %}

AppClub/templates/evento_list.html
{% extends 'padre.html' %}

{% block ContenidoQueCambia %}
<div class="container mt-4 mb-4">
    <div class="row">
        {% for evento in eventos %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <div class="card-body">
                        <p><strong style="text-transform: uppercase;">{{evento.deporte}}</strong></p>
                        <h3 class="card-title">{{ evento.titulo }}</h3>
                        <p class="card-text">{{ evento.fecha }}</p>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <a class="btn btn-primary btn-block" href="{% url 'detallarEventos' pk=evento.pk %}">Ver más</a>
                        {% if user.is_staff %}
                            <a class="btn btn-secondary btn-block" href="{% url 'actualizarEvento' evento.id %}">Editar</a>
                            <form action="{% url 'eliminarEventos' evento.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-secondary btn-block">Eliminar</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% empty %}
            <p>No hay eventos disponibles.</p>
        {% endfor %}
    </div>
</div>

{% endblock ContenidoQueCambia %}

AppClub/templates/inicio.html
{% extends 'padre.html' %}

{% block ContenidoQueCambia %}
<p> {{mensaje}} </p>
{% if user.is_staff %}

        <div class="row gx-4 gx-lg-5">
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">Noticias</h2>
                        <p class="card-text">Accede al formulario para crear nuevas noticias.</p>
                    </div>
                    <div class="card-footer"><a class="btn btn-primary btn-sm" href="{% url 'crearNoticias' %}">Crear
                            Noticia</a></div>
                </div>
            </div>
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">Deportes</h2>
                        <p class="card-text">Accede al formulario para crear nuevos deportes.</p>
                    </div>
                    <div class="card-footer"><a class="btn btn-primary btn-sm" href="{% url 'crearDeportes' %}">Crear Deporte</a></div>
                </div>
            </div>
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">Eventos</h2>
                        <p class="card-text">Accede al formulario para crear nuevos eventos.</p>
                    </div>
                    <div class="card-footer"><a class="btn btn-primary btn-sm" href="{% url 'crearEventos' %}">Crear Evento</a></div>
                </div>
            </div>
        </div>
{% endif %}    
        <div class="row mt-4 px-4 px-lg-5 gx-4 gx-lg-5 align-items-center mx-auto my-5">
            <div class="col-lg-7">
                <img class="img-fluid rounded mb-4 mb-lg-0"
                    src='https://th.bing.com/th/id/R.de5332d78d30002465b6833e0306f414?rik=WKZUzATy8fLkDA&pid=ImgRaw&r=0'
                    alt="Imagen Principal" width="500" height="300" />
            </div>
            <div class="col-lg-5">
                <h1 class="font-weight-light">Club Atletico Central Cordoba</h1>
                <p>Bienvenidos a la sede virtual del Club Atletico Central Cordoba de Rosario.<br> Aquí podrá asociarse,
                    consultar los
                    deportes y
                    eventos proximos!</p>
            </div>
        </div>
{% endblock ContenidoQueCambia %}

AppClub/templates/navbar.html
{% load static %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
            <div class="container px-5">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                        <li class="navbar-brand"><a class="nav-link" href="{% url 'Inicio' %}">Inicio</a>
                        <li class="navbar-brand"><a class="nav-link" href="{% url 'listarNoticias' %}">Noticias</a>
                        <li class="navbar-brand"><a class="nav-link" href="{% url 'listarEventos' %}">Eventos</a>
                        <li class="navbar-brand"><a class="nav-link" href="{% url 'listarDeportes' %}">Deportes</a>
                        <li class="navbar-brand"><a class="nav-link" href="{% url 'about_us' %}">Nosotros</a>
                        <li class="navbar-brand"><a class="nav-link" href="{% url 'contacto' %}">Contacto</a>
                        {% if user.is_authenticated %}
                        {% if user.avatar %}
                        <li> <img src="{{ user.avatar.url }}" alt="{{ user.username }} Avatar" style="width: 50px; height: 50px; object-fit: cover; border-radius: 50%;"> 
                        </li>
                        {% else %}
                        <li><img src="{% static 'default_avatar.png' %}" style="width: 50px; height: 50px; object-fit: cover; border-radius: 50%;" alt="Avatar por defecto"></li>
                        {% endif %}
                        <li class="navbar-brand"><a class="nav-link" href="{% url 'profile' %}">Mi Perfil</a>
                        <li class="navbar-brand"><a class="nav-link" href="{% url 'logout' %}">Cerrar sesion</a>
                        {% else %}
                        <li class="navbar-brand"><a class="nav-link" href="{% url 'login' %}">Iniciar sesion</a>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

AppClub/templates/noticia_detail.html
{% extends 'padre.html' %}
{% load static %}
{% block ContenidoQueCambia %}
<div class="row mt-4 px-4 px-lg-5 gx-4 gx-lg-5 align-items-center mx-auto my-5">
    <div class="col-lg-7">
        {% if noticia.imagen %}
        <img src="{{ noticia.imagen.url }}" alt="Imagen de Noticia" class="img-fluid w-100 h-auto">
        {% endif %}
        <br>
        <p><em>{{noticia.pie_de_foto}}</em></p>
    </div>
    <div class="col-lg-5">
        <p><strong style="text-transform: uppercase;">{{noticia.tema}}</strong></p>
        <h2 class="font-weight-light">{{noticia.titulo}}</h2>
        <h6>{{noticia.subtitulo}}</h6>
        <p>{{noticia.desarrollo}}</p>
        <p>Publicado el día {{noticia.fecha}} por <strong>{{noticia.autor}}</strong> </p>
    </div>
 {% if user.is_authenticated %}
      <div class="row mt-4">
        <div class="col-md-8">
        
          <h2>Deja un comentario</h2>
          <form method="post" action="{% url 'CrearComentario' noticia.id %}">
    {% csrf_token %}
    {{ comentario_form.as_p }}
    <button type="submit" class="btn btn-primary btn-block">Comentar</button>
</form>
        </div>
      </div>
    {% else %}
      <div class="row mt-4">
        <div class="col-md-8">
        <p>Inicia sesión para dejar un comentario. <a class="btn btn-primary btn-block" href="{% url 'login' %}">Inicia Sesión</a></p> 

        </div>
      </div>
    {% endif %}
    <h3>Comentarios</h3>
    {% for comentario in noticia.comentario_set.all %}
       <div class="comentario"> 
       {% if comentario.autor.avatar %}
        <img src="{{ comentario.autor.avatar.url }}"style="width: 40px; height: 40px; object-fit: cover; border-radius: 50%;" alt="Avatar" class="avatar-img">
        {% else %}
        <img src="{% static 'default_avatar.png' %}" style="width: 40px; height: 40px; object-fit: cover; border-radius: 50%;"height='50px' alt="Avatar por defecto" class="avatar-img">
        {% endif %}
           <strong>{{ comentario.autor.first_name }} {{ comentario.autor.last_name }}</strong>
           <p>{{ comentario.comentario }}</p>
           <p class="fecha">{{ comentario.fecha }}</p>
       </div>
    {% endfor %}
</div>
{% endblock ContenidoQueCambia %}

AppClub/templates/socio_create.html
{% extends 'padre.html' %}

{% block ContenidoQueCambia %}
<form action="{% url 'crearSocios' %}" method="post"> {% csrf_token %}
    {{form.as_p}}

    <button type="submit"> Asociarse </button>
</form>

{% endblock ContenidoQueCambia %}

AppClub/templates/socio_delete.html
{% extends 'padre.html' %}

{% block ContenidoQueCambia %}
<form action="{% url 'eliminarSocios' pk=socio.id %}" method="post"> {% csrf_token %}
    {{form.as_p}}

    <p>Está seguro que quiere eliminar el socio?</p>

    <button type="submit"> Confirmar </button>
    <button>="<a href="{% url 'Inicio' %}"></a>" Cancelar </button>
</form>

{% endblock ContenidoQueCambia %}